### ISSUE TITLE
Obtaining protein families from ChEMBL database

### ISSUE THREAD

**Issue by Tigerrr07** [cansyl/TransferLearning4DTI#1]
Hi there! 👋

I'm currently working on processing the ChEMBL database for my project, and I'm having trouble obtaining the six protein families: kinases, G-protein-coupled receptors (GPCRs), ion channels, nuclear receptors, proteases, and transporters.

I attempted to use the PREF_NAME key from the PROTEIN_CLASSIFICATION table, but I'm unable to connect them with the specified six protein families.

Could someone please guide me on the correct approach to classify proteins into aforementioned protein families? Any help or insights would be greatly appreciated!

Thank you in advance! 😊

**Comment by alperendalkiran** [comment]
Hi,

In our approach, first, we click Targets (15,398). Then, we select the protein families using the filter on the left side, Protein Classification L1 and Protein Classification L2. You may use L3 and l4 as well if you need it. After that, you should be able to download protein targets that belong to the selected protein family. 

We used the Activities tab and applied some filters in the second step. You may use the same protein classification filters in the previous step. After applying the filtering steps, you may download the activities for your protein family. 

I hope this helps you.

**Comment by Tigerrr07** [comment]
> Hi,
> 
> In our approach, first, we click Targets (15,398). Then, we select the protein families using the filter on the left side, Protein Classification L1 and Protein Classification L2. You may use L3 and l4 as well if you need it. After that, you should be able to download protein targets that belong to the selected protein family.
> 
> We used the Activities tab and applied some filters in the second step. You may use the same protein classification filters in the previous step. After applying the filtering steps, you may download the activities for your protein family.
> 
> I hope this helps you.

Thank you! Your provided process was really helpful!
